# Generated by Django 3.1.2 on 2020-12-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201204_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificado',
            options={'verbose_name': 'Clasificado', 'verbose_name_plural': 'Clasificados'},
        ),
    ]
