# Generated by Django 3.1.2 on 2020-12-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201209_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificado',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='planos/'),
        ),
    ]
