# Generated by Django 3.1.5 on 2021-01-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destacada', models.BooleanField(blank=True, default=False)),
                ('verificada', models.BooleanField(blank=True, default=False)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('tipologia', models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Casa Country', 'Casa Country'), ('PH', 'PH')], default='Departamento', max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('zonaprop', models.BooleanField(default=False)),
                ('properati', models.BooleanField(default=False)),
                ('argenprop', models.BooleanField(default=False)),
                ('mercadolibre', models.BooleanField(default=False)),
                ('reporteinmobiliario', models.BooleanField(default=False)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('barrio', models.CharField(choices=[('Agronomía', 'Agronomía'), ('Almagro', 'Almagro'), ('Balvanera', 'Balvanera'), ('Barracas', 'Barracas'), ('Belgrano', 'Belgrano'), ('Boedo', 'Boedo'), ('Caballito', 'Caballito'), ('Chacarita', 'Chacarita'), ('Coghlan', 'Coghlan'), ('Colegiales', 'Colegiales'), ('Constitucion', 'Constitucion'), ('Flores', 'Flores'), ('Floresta', 'Floresta'), ('La Boca', 'La Boca'), ('La Paternal', 'La Paternal'), ('Liniers', 'Liniers'), ('Mataderos', 'Mataderos'), ('Monte Castro', 'Monte Castro'), ('Monserrat', 'Monserrat'), ('Nueva Pompeya', 'Nueva Pompeya'), ('Núñez', 'Núñez'), ('Palermo', 'Palermo'), ('Parque Avellaneda', 'Parque Avellaneda'), ('Parque Chacabuco', 'Parque Chacabuco'), ('Parque Chas', 'Parque Chas'), ('Parque Patricios', 'Parque Patricios'), ('Puerto Madero', 'Puerto Madero'), ('Recoleta', 'Recoleta'), ('Retiro', 'Retiro'), ('Saavedra', 'Saavedra'), ('San Cristóbal', 'San Cristóbal'), ('San Nicolás', 'San Nicolás'), ('San Telmo', 'San Telmo'), ('Vélez Sárfield', 'Vélez Sárfield'), ('Versalles', 'Versalles'), ('Villa Crespo', 'Villa Crespo'), ('Villa del Parque', 'Villa del Parque'), ('Villa Devoto', 'Villa Devoto'), ('Villa General Mitre', 'Villa General Mitre'), ('Villa Lugano', 'Villa Lugano'), ('Villa Luro', 'Villa Luro'), ('Villa Ortúzar', 'Villa Ortúzar'), ('Villa Pueyrredón', 'Villa Pueyrredón'), ('Villa Real', 'Villa Real'), ('Villa Riachuelo', 'Villa Riachuelo'), ('Villa Santa Rita', 'Villa Santa Rita'), ('Villa Soldati', 'Villa Soldati'), ('Villa Urquiza', 'Villa Urquiza')], default='Agronomía', max_length=50)),
                ('cp', models.IntegerField(blank=True, default=0)),
                ('costo', models.IntegerField(blank=True, default=0)),
                ('moneda_costo', models.CharField(choices=[('$', '$'), ('USD', 'USD')], default='USD', max_length=50)),
                ('expensas', models.IntegerField(blank=True, default=0)),
                ('moneda_expensas', models.CharField(choices=[('$', '$'), ('USD', 'USD')], default='$', max_length=50)),
                ('luz', models.IntegerField(blank=True, default=0)),
                ('gas', models.IntegerField(blank=True, default=0)),
                ('abl', models.IntegerField(blank=True, default=0)),
                ('aysa', models.IntegerField(blank=True, default=0)),
                ('m2_totales', models.IntegerField(blank=True, default=0)),
                ('m2_cubiertos', models.IntegerField(blank=True, default=0)),
                ('piso', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('depto', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default='A', max_length=50)),
                ('ambientes', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('dormitorios', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('banios', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('orientacion', models.CharField(choices=[('Norte', 'Norte'), ('Noreste', 'Noreste'), ('Este', 'Este'), ('Sudeste', 'Sudeste'), ('Sur', 'Sur'), ('Sudoeste', 'Sudoeste'), ('Oeste', 'Oeste'), ('Noroeste', 'Noroeste')], default='Norte', max_length=50)),
                ('antiguedad', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('cochera', models.BooleanField(default=False)),
                ('cocheras', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10)),
                ('baulera', models.BooleanField(default=False)),
                ('pileta', models.BooleanField(default=False)),
                ('gimnasio', models.BooleanField(default=False)),
                ('juegos', models.BooleanField(default=False)),
                ('solarium', models.BooleanField(default=False)),
                ('microcine', models.BooleanField(default=False)),
                ('parrilla', models.BooleanField(default=False)),
                ('salon_usos_multiples', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('alarma', models.BooleanField(default=False)),
                ('mascotas', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('losa_radiante', models.BooleanField(default=False)),
                ('internet', models.CharField(choices=[('-', '-'), ('Fibertel', 'Fibertel'), ('Arnet', 'Arnet'), ('Telecentro', 'Telecentro'), ('Cablevision', 'Cablevision'), ('DirecTV', 'DirecTV')], default='-', max_length=50)),
                ('cable', models.CharField(choices=[('-', '-'), ('Fibertel', 'Fibertel'), ('Arnet', 'Arnet'), ('Telecentro', 'Telecentro'), ('Cablevision', 'Cablevision'), ('DirecTV', 'DirecTV')], default='-', max_length=50)),
            ],
            options={
                'verbose_name': 'Clasificado',
                'verbose_name_plural': 'Clasificados',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Comprador', 'Comprador'), ('Ambas', 'Ambas')], default='Vendedor', max_length=50)),
                ('testimonio', models.CharField(blank=True, max_length=50)),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
