# Generated by Django 3.1.5 on 2021-01-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
