# Generated by Django 3.1.5 on 2021-01-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210111_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='valuacion_propiedad',
        ),
    ]
