# Generated by Django 3.1.5 on 2021-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_clasificado_imagen_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('General', 'General'), ('Servicio', 'Servicio'), ('Post-Publicación', 'Post-Publicación')], default='General', max_length=50)),
                ('pregunta', models.CharField(blank=True, max_length=100)),
                ('respuesta', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQS',
            },
        ),
    ]
