# Generated by Django 3.1.5 on 2021-01-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_remove_pack_valuacion_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='valuacion_propiedad',
            field=models.BooleanField(default=False),
        ),
    ]
