# Generated by Django 3.1.5 on 2021-01-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_pack_valuacion_propiedad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pack',
            options={'verbose_name': 'Pack', 'verbose_name_plural': 'Packs'},
        ),
        migrations.AddField(
            model_name='pack',
            name='ambientacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='asesoramiento_legal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='borradores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='cartel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='estudio_titulos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='experto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='ficha_tecnica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='financiacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='gestion_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='publicacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='redaccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='reportes_semanales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='secretario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='soporte_post_venta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='visitas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pack',
            name='visitas_acompanadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pack',
            name='precio',
            field=models.IntegerField(default=10),
        ),
    ]
