# Generated by Django 3.1.5 on 2021-01-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='mapa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
