# Generated by Django 3.1.5 on 2021-01-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_clasificado_mapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='testimonio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='mensaje',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
