# Generated by Django 3.1.5 on 2021-01-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_auto_20210121_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqs',
            name='respuestas',
        ),
        migrations.AlterField(
            model_name='faqs',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
