# Generated by Django 3.1.5 on 2021-01-21 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_auto_20210121_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faqs',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
