# Generated by Django 3.1.5 on 2021-01-21 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_clasificado_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='galeria/')),
                ('nombre', models.CharField(max_length=50)),
                ('propiedad', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hello.clasificado')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
    ]
