# Generated by Django 3.1.5 on 2021-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cp_ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
