# Generated by Django 3.1.5 on 2021-01-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_usuario_cp_ciudad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificado',
            old_name='alarma',
            new_name='seguridad',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='abl',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='aysa',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='baulera',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='losa_radiante',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='luz',
        ),
        migrations.RemoveField(
            model_name='clasificado',
            name='mascotas',
        ),
        migrations.AddField(
            model_name='clasificado',
            name='cant_de_pisos',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='depto_por_piso',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21')], default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='tour',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
