# Generated by Django 3.1.5 on 2021-01-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_auto_20210125_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='disposicion',
            field=models.CharField(choices=[('Frente', 'Frente'), ('Contrafrente', 'Contrafrente')], default='Frente', max_length=15),
        ),
    ]
