# Generated by Django 3.1.5 on 2021-01-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_clasificado_disposicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='visita',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
