# Generated by Django 3.1.5 on 2021-01-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_clasificado_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificado',
            name='img_tour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='clasificado',
            name='img_youtube',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pack',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
